[package]
name = "torm"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
ratatui = { version = "0.29.0", features = ["crossterm"] }
tokio = { version = "1.44.1", features = ["full"] }
